# Python Problem Solving

This portfolio notebook demonstrates foundational Python problem-solving using functions, loops, validation, numerical approximation, and NumPy array logic.

## Skills Demonstrated

- Writing reusable Python functions
- Input validation
- `while` and `for` loops
- Numerical approximation
- NumPy indexing and Boolean masks
- Clear, testable programming logic

> **Note:** This notebook is a portfolio adaptation of coursework completed while learning Python.

In [1]:
import numpy as np

## Factorial Function

The factorial of a positive integer is the product of that integer and every positive integer below it. This implementation uses a `while` loop.

In [2]:
def factorial(n):
    if not isinstance(n, int) or n < 0:
        raise ValueError("n must be a non-negative integer")

    result = 1
    while n > 1:
        result *= n
        n -= 1

    return result

print(factorial(5))

120


## Positive Divisors

The `div(n)` function returns every positive divisor of a positive integer and validates the input before performing the calculation.

In [3]:
def div(n):
    if not isinstance(n, int):
        raise TypeError("n must be an integer")

    if n <= 0:
        raise ValueError("n must be positive")

    divisors = []

    for i in range(1, n + 1):
        if n % i == 0:
            divisors.append(i)

    return divisors

print(div(12))

[1, 2, 3, 4, 6, 12]


## Numerical Derivative Approximation

A derivative can be approximated numerically by measuring how much a function changes over a very small interval.

In [4]:
def deriv(f, a, h=0.001):
    return (f(a + h) - f(a)) / h

def f1(x):
    return x**2 - 3*x + 4

def f2(x):
    return x**3 + x**2 - 3*x

print(f"Approximate derivative of f1 at x=5: {deriv(f1, 5):.3f}")
print(f"Approximate derivative of f2 at x=1: {deriv(f2, 1):.3f}")

Approximate derivative of f1 at x=5: 7.001
Approximate derivative of f2 at x=1: 2.004


## NumPy Array Indexing

NumPy arrays allow data to be organized into rows and columns and selected efficiently by position.

In [5]:
wa = np.arange(20).reshape(4, 5)

print("Array:")
print(wa)

print("\nSecond row:")
print(wa[1])

print("\nThird column:")
print(wa[:, 2])

print("\nBottom-right value:")
print(wa[-1, -1])

Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Second row:
[5 6 7 8 9]

Third column:
[ 2  7 12 17]

Bottom-right value:
19


## Boolean Masks

Boolean masks provide a concise way to filter an array using logical conditions.

In [6]:
mask = (wa < 5) | (wa > 16)

selected_values = wa[mask]

print("Values less than 5 or greater than 16:")
print(selected_values)

Values less than 5 or greater than 16:
[ 0  1  2  3  4 17 18 19]


## Summary

These examples demonstrate core Python concepts that support more advanced data science work: writing functions, validating inputs, applying loops and conditions, approximating numerical results, and selecting data efficiently with NumPy.